CREATE OR REPLACE TABLE CUMULATIVE_RETURNS AS
SELECT
    NAME,
    DATE,
    CLOSE,
    (CLOSE / FIRST_VALUE(CLOSE) OVER (PARTITION BY NAME ORDER BY DATE)) - 1 AS CUMULATIVE_RETURN
FROM ALL_STOCKS_5YR;

CREATE OR REPLACE TABLE DAILY_HIGH_LOW_DIFFERENCE AS
SELECT
    NAME,
    DATE,
    HIGH - LOW AS DAILY_DIFFERENCE
FROM ALL_STOCKS_5YR;

CREATE OR REPLACE TABLE TOP_5_VOLUME AS
SELECT
    NAME,
    SUM(VOLUME) AS TOTAL_VOLUME
FROM ALL_STOCKS_5YR
GROUP BY NAME
ORDER BY TOTAL_VOLUME DESC
LIMIT 5;

CREATE OR REPLACE TABLE TOP_5_AVG_CLOSE AS
SELECT NAME, AVG(CLOSE) AS AVG_CLOSE
FROM ALL_STOCKS_5YR
GROUP BY NAME
ORDER BY AVG_CLOSE DESC
LIMIT 5;
