SELECT * 
FROM "ETL_PIPELINE_DB"."ETL_SCHEMA"."ALL_STOCKS_5YR"
LIMIT 10;

SELECT * 
FROM top_5_avg_close;

SELECT * 
FROM monthly_avg_volume 
LIMIT 10;

SHOW TABLES;

USE DATABASE ETL_PIPELINE_DB;
USE SCHEMA ETL_SCHEMA;
